export const categories = [
  "Automotive",
  "Auto Paint Shops",
  "Auto Parts",
  "Auto Repair Shops",
  "Auto and Home Supply Stores",
  "Automobile Associations",
  "Boat Dealers",
  "Body Shops",
  "Camper Dealers, Recreational and Utility Trailers",
  "Car Dealerships",
  "Car Washes",
  "Cycle Stores",
  "Electric Vehicle Charging",
  "Fuel Dispensers",
  "Fuel Stations",
  "Motorcycle Shops and Dealers",
  "Petroleum Products",
  "RV Rentals",
  "RV Sales",
  "Snowmobile Dealers",
  "Tire Repair",
  "Tire Stores",
  "Towing",
  "Truck Rentals",
  "Used Truck Dealers",
  "Vehicle Equipment Supplies",
  "Bill Payments",
  "Cable, Satellite Bill Payments",
  "Internet Services",
  "Phone Bills",
  "Wallet Loading - B2B Bill payment",
  "Digital Goods",
  "Software Applications (Excluding Games)",
  "Subscription for audiobooks, news, entertainment",
  "Ecommerce/Retail",
  "Alcohol stores",
  "Antique Stores",
  "Bakeries",
  "Bookstores",
  "Clothing Stores",
  "Cosmetics",
  "Department Stores",
  "Electronics Stores",
  "Furniture Stores",
  "Gift Shops",
  "Jewelry Stores",
  "Toy Stores",
  "Education",
  "Colleges & Universities",
  "Electronics & Appliances",
  "Entertainment & Recreation",
  "Financial Services",
  "Banks/NBFC",
  "Payment Service Provider",
  "Stock broking/Mutual Funds",
  "Gaming",
  "Government Services",
  "Grocery & Supermarkets",
  "Healthcare & Medical",
  "Hospitals",
  "Pharmacies",
  "Home Improvement",
  "Hotels & Lodging",
  "Hotels",
  "Insurance",
  "Logistics",
  "Non-Profit",
  "Charities",
  "Personal Services",
  "Salons & Barber Shops",
  "Professional Services",
  "IT Services",
  "Legal Services",
  "Real Estate",
  "Restaurants & Dining",
  "Fast Food",
  "Transportation",
  "Courier Services",
  "Public Transport",
  "Travel",
  "Airlines",
  "Travel Agencies",
  "Utilities",
  "Electricity/Water/Gas Bill Payment Only"
];
